INSERT INTO detail(name, price, size) values('автоматическая корбка передач', '31436','40');
INSERT INTO detail(name, price, size) values('круиз-контроль', '8377','20');
INSERT INTO detail(name, price, size) values('аккамулятор', '1634','10');
INSERT INTO detail(name, price, size) values('амортизатор', '8165','30');
INSERT INTO detail(name, price, size) values('спортивный глушитель', '6205','40');
INSERT INTO detail(name, price, size) values(' бензиновый двигатель', '43115','10');
INSERT INTO detail(name, price, size) values('сабвуфер', '13494','40');
INSERT INTO detail(name, price, size) values('стеклоподъёмник', '1072','50');
INSERT INTO detail(name, price, size) values('вариатор', '19210','50');
INSERT INTO detail(name, price, size) values('люк без электропривода', '13745','10');
INSERT INTO detail(name, price, size) values('освежитель-ароматизатор воздуха', '255','30');
INSERT INTO detail(name, price, size) values('буксирный трос', '490','40');
INSERT INTO detail(name, price, size) values('педаль газа', '8099','10');
INSERT INTO detail(name, price, size) values('головка блока цилиндров', '8738','20');
INSERT INTO detail(name, price, size) values('автоаптечка', '2402','20');
INSERT INTO detail(name, price, size) values('спойлер по низу бампера', '466','10');
INSERT INTO detail(name, price, size) values('решётка радиатора', '19062','40');
INSERT INTO detail(name, price, size) values('крышка топливного бака', '17431','10');
INSERT INTO detail(name, price, size) values('фары', '7176','30');
INSERT INTO detail(name, price, size) values('зимняя резина шипы 12 дюймов', '19071','10');
INSERT INTO detail(name, price, size) values('зимняя резина шипы 14 дюймов', '12367','50');
INSERT INTO detail(name, price, size) values('зимняя резина шипы 16 дюймов', '1756','10');
INSERT INTO detail(name, price, size) values('зимняя резина шипы 18 дюймов', '13740','20');
INSERT INTO detail(name, price, size) values('зимняя резина шипы 20 дюймов', '12404','20');
INSERT INTO detail(name, price, size) values('зимняя резина липучки 12 дюймов', '19935','30');
INSERT INTO detail(name, price, size) values('зимняя резина липучки 14 дюймов', '15881','20');
INSERT INTO detail(name, price, size) values('зимняя резина липучки 16 дюймов', '12883','20');
INSERT INTO detail(name, price, size) values('зимняя резина липучки 18 дюймов', '19147','30');
INSERT INTO detail(name, price, size) values('зимняя резина липучки 20 дюймов', '18912','20');
INSERT INTO detail(name, price, size) values('летняя резина 12 дюймов', '3824','40');
INSERT INTO detail(name, price, size) values('летняя резина 14 дюймов', '7591','30');
INSERT INTO detail(name, price, size) values('летняя резина 16 дюймов', '10033','30');
INSERT INTO detail(name, price, size) values('летняя резина 18 дюймов', '15396','20');
INSERT INTO detail(name, price, size) values('летняя резина 20 дюймов', '19100','40');
INSERT INTO detail(name, price, size) values('кондиционер', '2922','50');
INSERT INTO detail(name, price, size) values('коленчатый вал', '729','30');
INSERT INTO detail(name, price, size) values('проигрыватель компактов дисков', '15517','30');
INSERT INTO detail(name, price, size) values('задние стопари', '17601','20');
INSERT INTO detail(name, price, size) values('механическая коробка передач', '12770','50');
INSERT INTO detail(name, price, size) values('рычаг переключения передач', '17751','50');
INSERT INTO detail(name, price, size) values('люк', '5079','50');
INSERT INTO detail(name, price, size) values('пусковая рукоятка двигателя', '3719','40');
INSERT INTO detail(name, price, size) values('литые диски', '4760','40');
INSERT INTO detail(name, price, size) values('аппарель', '7705','30');
INSERT INTO detail(name, price, size) values('даунпайп', '14030','40');
INSERT INTO detail(name, price, size) values('турбина', '842','20');
INSERT INTO detail(name, price, size) values('ремень безопасности', '8728','50');
INSERT INTO detail(name, price, size) values('ремень грм', '3292','10');
INSERT INTO detail(name, price, size) values('кожанный чехол на капот', '2517','50');
INSERT INTO detail(name, price, size) values('капот', '12051','30');
INSERT INTO detail(name, price, size) values('амортизатор', '16644','20');
INSERT INTO detail(name, price, size) values('стеклоочиститель', '3553','30');
INSERT INTO detail(name, price, size) values('топливный фильтр', '10908','20');
INSERT INTO detail(name, price, size) values('топливный насос', '5737','50');
INSERT INTO detail(name, price, size) values('свечи', '19535','10');
INSERT INTO detail(name, price, size) values('дворники', '11374','10');
INSERT INTO detail(name, price, size) values('распределительный вал', '2746','10');
INSERT INTO detail(name, price, size) values('педаль сцепления', '10123','20');
INSERT INTO detail(name, price, size) values('педаль тормоза', '16203','10');
INSERT INTO detail(name, price, size) values('дефлектор капота', '9615','50');
INSERT INTO detail(name, price, size) values('воздухозаборник', '16450','50');
INSERT INTO detail(name, price, size) values('низкие декоративные пороги', '13437','50');
INSERT INTO detail(name, price, size) values('гидроуселитель руля', '4518','20');
INSERT INTO detail(name, price, size) values('тонировочная плёнка', '2744','10');
INSERT INTO detail(name, price, size) values('кондиционер', '17249','30');
INSERT INTO detail(name, price, size) values('ручной тормоз', '2510','50');
INSERT INTO detail(name, price, size) values('форсунки омывания стекла', '11195','20');
INSERT INTO detail(name, price, size) values('высокий спойлер на крыше багажника', '1147','40');
INSERT INTO detail(name, price, size) values('зеркало заднего вида', '9532','50');
INSERT INTO detail(name, price, size) values('боковое зеркало левое', '3217','40');
INSERT INTO detail(name, price, size) values('боковое зеркало правое', '3494','10');
INSERT INTO detail(name, price, size) values('передний бампер', '8329','40');
INSERT INTO detail(name, price, size) values('подкрылки', '2552','40');
INSERT INTO detail(name, price, size) values('диск сцепления', '7586','20');
INSERT INTO detail(name, price, size) values('спойлер', '13923','20');
INSERT INTO detail(name, price, size) values('подвеска', '12910','50');
INSERT INTO detail(name, price, size) values('стептроник', '17809','50');
INSERT INTO detail(name, price, size) values('сигнализация', '17599','20');
INSERT INTO detail(name, price, size) values('автомагнитола', '14735','10');
INSERT INTO detail(name, price, size) values('подушка безопасности', '6485','50');
INSERT INTO detail(name, price, size) values('аэродинамический обвес', '16888','10');
INSERT INTO detail(name, price, size) values('рычаг стабилизатора поперечной устойчивости', '10401','30');
INSERT INTO detail(name, price, size) values('картер', '15815','50');
INSERT INTO detail(name, price, size) values('дифференцм=иал', '8666','30');
INSERT INTO detail(name, price, size) values('редуктор', '17824','40');
INSERT INTO detail(name, price, size) values('карбюратор', '1630','30');
INSERT INTO detail(name, price, size) values('инжектор', '12299','10');
INSERT INTO detail(name, price, size) values('стартер', '12409','30');
INSERT INTO detail(name, price, size) values('кардан', '15873','30');
INSERT INTO detail(name, price, size) values('впускной коллектор', '14545','20');
INSERT INTO detail(name, price, size) values('выпускной коллектор', '2703','40');
INSERT INTO detail(name, price, size) values('сальники', '231','50');
INSERT INTO detail(name, price, size) values('маслосъёмные кольца', '1749','20');
INSERT INTO detail(name, price, size) values('реле', '9167','40');
INSERT INTO detail(name, price, size) values('тахометр', '4726','40');
INSERT INTO detail(name, price, size) values('релинг', '3534','30');
INSERT INTO detail(name, price, size) values('преднатяжители ремней', '2396','50');
INSERT INTO detail(name, price, size) values('климат контроль', '20','30');
INSERT INTO detail(name, price, size) values('воздушный фильтр', '11490','50');
INSERT INTO detail(name, price, size) values('масляный фильтр', '9184','40');