INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Авторусь', '1','1 MONTH 11 DAY','10 YEAR 4 MONTH','84559534','2');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('24зап', '1','3 MONTH 29 DAY','10 YEAR 7 MONTH','54853104','4');
INSERT INTO supplier(name, type, delivery_time) values('AD Avanta','2','1 MONTH 25 DAY');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Alluniparts','1','1 MONTH 11 DAY','7 YEAR 12 MONTH','18090034','55');
INSERT INTO supplier(name, type, delivery_time) values('Autolans','2','4 MONTH 8 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Forward Autoparts','2','3 MONTH 2 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Gparts import','2','1 MONTH 12 DAY');
INSERT INTO supplier(name, type, delivery_time) values('IXORA','2','6 MONTH 12 DAY');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('JpAuto','1','1 MONTH 28 DAY','6 YEAR 4 MONTH','93412734','54');
INSERT INTO supplier(name, type, delivery_time) values('MYSTORE1','2','5 MONTH 13 DAY');
INSERT INTO supplier(name, type, delivery_time) values('ААА-Авто','2','2 MONTH 31 DAY');
INSERT INTO supplier(name, type, delivery_time) values('АБС-Авто','2','6 MONTH 25 DAY');
INSERT INTO supplier(name, type, delivery_time) values('АВД-Моторс','2','1 MONTH 4 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Авто Фактор Про','2','2 MONTH 12 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Авто-Евро','2','5 MONTH 10 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Авто-закуп','2','6 MONTH 28 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Авто-Инсайд','2','2 MONTH 6 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Авто-мир','2','4 MONTH 11 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Авто-Стратегия','2','4 MONTH 7 DAY');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автоартис','1','1 MONTH 14 DAY','1 YEAR 5 MONTH','68453215','12');
INSERT INTO supplier(name, type, delivery_time) values('Автогут','2','3 MONTH 29 DAY');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автодок','1','2 MONTH 0 DAY','1 YEAR 5 MONTH','24593388','6');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автозапчасти быстро','1','1 MONTH 14 DAY','1 YEAR 5 MONTH','98653212','8');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автокас','1','0 MONTH 14 DAY','1 YEAR 5 MONTH','87542165','25');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автоклондайк','1','1 MONTH 0 DAY','1 YEAR 5 MONTH','95846251','20');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автоконтинент','1','0 MONTH 14 DAY','1 YEAR 5 MONTH','53425342','4');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автолига','1','1 MONTH 20 DAY','1 YEAR 5 MONTH','86752435','1');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автологист','1','2 MONTH 14 DAY','1 YEAR 5 MONTH','98126545','5');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автомобильность','1','4 MONTH 0 DAY','1 YEAR 5 MONTH','78326535','2');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('АвтоМотоТрейд','1','1 MONTH 0 DAY','1 YEAR 5 MONTH','79845162','16');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Автонит','1','1 MONTH 14 DAY','3 YEAR 5 MONTH','91827346','19');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Берг','1','1 MONTH 26 DAY','2 YEAR 5 MONTH','65798266','17');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Бигодин','1','1 MONTH 10 DAY','1 YEAR 5 MONTH','11246897','12');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Вемас','1','6 MONTH 11 DAY','3 YEAR 10 MONTH','86211937','74');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Винсейл','1','5 MONTH 10 DAY','10 YEAR 1 MONTH','70935332','43');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Вира Плюс','1','2 MONTH 8 DAY','4 YEAR 12 MONTH','39874019','81');
INSERT INTO supplier(name, type, delivery_time) values('Гесвар','2','5 MONTH 13 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Гуд-Авто','2','1 MONTH 28 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Дарс','2','3 MONTH 9 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Джапартс','2','5 MONTH 10 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Фаворит-Авто','2','2 MONTH 21 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Емекс','2','1 MONTH 16 DAY');
INSERT INTO supplier(name, type, delivery_time) values('ЗОМавто','2','2 MONTH 28 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Империя авто','2','3 MONTH 18 DAY');
INSERT INTO supplier(name, type, delivery_time, guarantee, contract, discount) values('Gforce FZE','1','2 MONTH 1 DAY','10 YEAR 9 MONTH','38859647','18');
INSERT INTO supplier(name, type, delivery_time) values('РМС Авто','2','4 MONTH 23 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Партсиб','2','4 MONTH 31 DAY');
INSERT INTO supplier(name, type, delivery_time) values('ПартПлюс 54','2','1 MONTH 9 DAY');
INSERT INTO supplier(name, type, delivery_time) values('НормАвто','2','1 MONTH 15 DAY');
INSERT INTO supplier(name, type, delivery_time) values('Микало','2','3 MONTH 6 DAY');