INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('1', 'Авторусь', '1','1 MONTH 11 DAY','10 YEAR 4 MONTH','84559534','2');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('2', '24зап', '1','3 MONTH 29 DAY','10 YEAR 7 MONTH','54853104','4');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('3', 'AD Avanta','2','1 MONTH 25 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('4', 'Alluniparts','1','1 MONTH 11 DAY','7 YEAR 12 MONTH','18090034','55');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('5', 'Autolans','2','4 MONTH 8 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('6', 'Forward Autoparts','2','3 MONTH 2 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('7', 'Gparts import','2','1 MONTH 12 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('8', 'IXORA','2','6 MONTH 12 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('9','JpAuto','1','1 MONTH 28 DAY','6 YEAR 4 MONTH','93412734','54');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('10','MYSTORE1','2','5 MONTH 13 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('11', 'ААА-Авто','2','2 MONTH 31 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('12', 'АБС-Авто','2','6 MONTH 25 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('13','АВД-Моторс','2','1 MONTH 4 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('14','Авто Фактор Про','2','2 MONTH 12 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('15','Авто-Евро','2','5 MONTH 10 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('16','Авто-закуп','2','6 MONTH 28 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('17','Авто-Инсайд','2','2 MONTH 6 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('18','Авто-мир','2','4 MONTH 11 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('19','Авто-Стратегия','2','4 MONTH 7 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('20','Автоартис','1','1 MONTH 14 DAY','1 YEAR 5 MONTH','68453215','12');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('21','Автогут','2','3 MONTH 29 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('22','Автодок','1','2 MONTH 0 DAY','1 YEAR 5 MONTH','24593388','6');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('23','Автозапчасти быстро','1','1 MONTH 14 DAY','1 YEAR 5 MONTH','98653212','8');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('24','Автокас','1','0 MONTH 14 DAY','1 YEAR 5 MONTH','87542165','25');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('25','Автоклондайк','1','1 MONTH 0 DAY','1 YEAR 5 MONTH','95846251','20');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('26','Автоконтинент','1','0 MONTH 14 DAY','1 YEAR 5 MONTH','53425342','4');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('27','Автолига','1','1 MONTH 20 DAY','1 YEAR 5 MONTH','86752435','1');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('28','Автологист','1','2 MONTH 14 DAY','1 YEAR 5 MONTH','98126545','5');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('29','Автомобильность','1','4 MONTH 0 DAY','1 YEAR 5 MONTH','78326535','2');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('30','АвтоМотоТрейд','1','1 MONTH 0 DAY','1 YEAR 5 MONTH','79845162','16');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('31','Автонит','1','1 MONTH 14 DAY','3 YEAR 5 MONTH','91827346','19');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('32','Берг','1','1 MONTH 26 DAY','2 YEAR 5 MONTH','65798266','17');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('33','Бигодин','1','1 MONTH 10 DAY','1 YEAR 5 MONTH','11246897','12');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('34','Вемас','1','6 MONTH 11 DAY','3 YEAR 10 MONTH','86211937','74');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('35','Винсейл','1','5 MONTH 10 DAY','10 YEAR 1 MONTH','70935332','43');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('36','Вира Плюс','1','2 MONTH 8 DAY','4 YEAR 12 MONTH','39874019','81');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('37','Гесвар','2','5 MONTH 13 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('38','Гуд-Авто','2','1 MONTH 28 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('39','Дарс','2','3 MONTH 9 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('40','Джапартс','2','5 MONTH 10 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('41','Фаворит-Авто','2','2 MONTH 21 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('42','Емекс','2','1 MONTH 16 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('43','ЗОМавто','2','2 MONTH 28 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('44','Империя авто','2','3 MONTH 18 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time, guarantee, contract, discount) values('45','Gforce FZE','1','2 MONTH 1 DAY','10 YEAR 9 MONTH','38859647','18');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('46','РМС Авто','2','4 MONTH 23 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('47','Партсиб','2','4 MONTH 31 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('48','ПартПлюс 54','2','1 MONTH 9 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('49','НормАвто','2','1 MONTH 15 DAY');
INSERT INTO supplier(supplierid, name, type, delivery_time) values('50','Микало','2','3 MONTH 6 DAY');