INSERT INTO detail(detailid, name, price, size) values('1', 'автоматическая корбка передач', '31436','40');
INSERT INTO detail(detailid, name, price, size) values('2', 'круиз-контроль', '8377','20');
INSERT INTO detail(detailid, name, price, size) values('3', 'аккамулятор', '1634','10');
INSERT INTO detail(detailid, name, price, size) values('4', 'амортизатор', '8165','30');
INSERT INTO detail(detailid, name, price, size) values('5', 'спортивный глушитель', '6205','40');
INSERT INTO detail(detailid, name, price, size) values('6', ' бензиновый двигатель', '43115','10');
INSERT INTO detail(detailid, name, price, size) values('7', 'сабвуфер', '13494','40');
INSERT INTO detail(detailid, name, price, size) values('8', 'стеклоподъёмник', '1072','50');
INSERT INTO detail(detailid, name, price, size) values('9', 'вариатор', '19210','50');
INSERT INTO detail(detailid, name, price, size) values('10', 'люк без электропривода', '13745','10');
INSERT INTO detail(detailid, name, price, size) values('11', 'освежитель-ароматизатор воздуха', '255','30');
INSERT INTO detail(detailid, name, price, size) values('12', 'буксирный трос', '490','40');
INSERT INTO detail(detailid, name, price, size) values('13', 'педаль газа', '8099','10');
INSERT INTO detail(detailid, name, price, size) values('14', 'головка блока цилиндров', '8738','20');
INSERT INTO detail(detailid, name, price, size) values('15', 'автоаптечка', '2402','20');
INSERT INTO detail(detailid, name, price, size) values('16', 'спойлер по низу бампера', '466','10');
INSERT INTO detail(detailid, name, price, size) values('17', 'решётка радиатора', '19062','40');
INSERT INTO detail(detailid, name, price, size) values('18', 'крышка топливного бака', '17431','10');
INSERT INTO detail(detailid, name, price, size) values('19', 'фары', '7176','30');
INSERT INTO detail(detailid, name, price, size) values('20', 'зимняя резина шипы 12 дюймов', '19071','10');
INSERT INTO detail(detailid, name, price, size) values('21', 'зимняя резина шипы 14 дюймов', '12367','50');
INSERT INTO detail(detailid, name, price, size) values('22', 'зимняя резина шипы 16 дюймов', '1756','10');
INSERT INTO detail(detailid, name, price, size) values('23', 'зимняя резина шипы 18 дюймов', '13740','20');
INSERT INTO detail(detailid, name, price, size) values('24', 'зимняя резина шипы 20 дюймов', '12404','20');
INSERT INTO detail(detailid, name, price, size) values('25', 'зимняя резина липучки 12 дюймов', '19935','30');
INSERT INTO detail(detailid, name, price, size) values('26', 'зимняя резина липучки 14 дюймов', '15881','20');
INSERT INTO detail(detailid, name, price, size) values('27', 'зимняя резина липучки 16 дюймов', '12883','20');
INSERT INTO detail(detailid, name, price, size) values('28', 'зимняя резина липучки 18 дюймов', '19147','30');
INSERT INTO detail(detailid, name, price, size) values('29', 'зимняя резина липучки 20 дюймов', '18912','20');
INSERT INTO detail(detailid, name, price, size) values('30', 'летняя резина 12 дюймов', '3824','40');
INSERT INTO detail(detailid, name, price, size) values('31', 'летняя резина 14 дюймов', '7591','30');
INSERT INTO detail(detailid, name, price, size) values('32', 'летняя резина 16 дюймов', '10033','30');
INSERT INTO detail(detailid, name, price, size) values('33', 'летняя резина 18 дюймов', '15396','20');
INSERT INTO detail(detailid, name, price, size) values('34', 'летняя резина 20 дюймов', '19100','40');
INSERT INTO detail(detailid, name, price, size) values('35', 'кондиционер', '2922','50');
INSERT INTO detail(detailid, name, price, size) values('36', 'коленчатый вал', '729','30');
INSERT INTO detail(detailid, name, price, size) values('37', 'проигрыватель компактов дисков', '15517','30');
INSERT INTO detail(detailid, name, price, size) values('38', 'задние стопари', '17601','20');
INSERT INTO detail(detailid, name, price, size) values('39', 'механическая коробка передач', '12770','50');
INSERT INTO detail(detailid, name, price, size) values('40', 'рычаг переключения передач', '17751','50');
INSERT INTO detail(detailid, name, price, size) values('41', 'люк', '5079','50');
INSERT INTO detail(detailid, name, price, size) values('42', 'пусковая рукоятка двигателя', '3719','40');
INSERT INTO detail(detailid, name, price, size) values('43', 'литые диски', '4760','40');
INSERT INTO detail(detailid, name, price, size) values('44', 'аппарель', '7705','30');
INSERT INTO detail(detailid, name, price, size) values('45', 'даунпайп', '14030','40');
INSERT INTO detail(detailid, name, price, size) values('46', 'турбина', '842','20');
INSERT INTO detail(detailid, name, price, size) values('47', 'ремень безопасности', '8728','50');
INSERT INTO detail(detailid, name, price, size) values('48', 'ремень грм', '3292','10');
INSERT INTO detail(detailid, name, price, size) values('49', 'кожанный чехол на капот', '2517','50');
INSERT INTO detail(detailid, name, price, size) values('50', 'капот', '12051','30');
INSERT INTO detail(detailid, name, price, size) values('51', 'амортизатор', '16644','20');
INSERT INTO detail(detailid, name, price, size) values('52', 'стеклоочиститель', '3553','30');
INSERT INTO detail(detailid, name, price, size) values('53', 'топливный фильтр', '10908','20');
INSERT INTO detail(detailid, name, price, size) values('54', 'топливный насос', '5737','50');
INSERT INTO detail(detailid, name, price, size) values('55', 'свечи', '19535','10');
INSERT INTO detail(detailid, name, price, size) values('56', 'дворники', '11374','10');
INSERT INTO detail(detailid, name, price, size) values('57', 'распределительный вал', '2746','10');
INSERT INTO detail(detailid, name, price, size) values('58', 'педаль сцепления', '10123','20');
INSERT INTO detail(detailid, name, price, size) values('59', 'педаль тормоза', '16203','10');
INSERT INTO detail(detailid, name, price, size) values('60', 'дефлектор капота', '9615','50');
INSERT INTO detail(detailid, name, price, size) values('61', 'воздухозаборник', '16450','50');
INSERT INTO detail(detailid, name, price, size) values('62', 'низкие декоративные пороги', '13437','50');
INSERT INTO detail(detailid, name, price, size) values('63', 'гидроуселитель руля', '4518','20');
INSERT INTO detail(detailid, name, price, size) values('64', 'тонировочная плёнка', '2744','10');
INSERT INTO detail(detailid, name, price, size) values('65', 'кондиционер', '17249','30');
INSERT INTO detail(detailid, name, price, size) values('66', 'ручной тормоз', '2510','50');
INSERT INTO detail(detailid, name, price, size) values('67', 'форсунки омывания стекла', '11195','20');
INSERT INTO detail(detailid, name, price, size) values('68', 'высокий спойлер на крыше багажника', '1147','40');
INSERT INTO detail(detailid, name, price, size) values('69', 'зеркало заднего вида', '9532','50');
INSERT INTO detail(detailid, name, price, size) values('70', 'боковое зеркало левое', '3217','40');
INSERT INTO detail(detailid, name, price, size) values('71', 'боковое зеркало правое', '3494','10');
INSERT INTO detail(detailid, name, price, size) values('72', 'передний бампер', '8329','40');
INSERT INTO detail(detailid, name, price, size) values('73', 'подкрылки', '2552','40');
INSERT INTO detail(detailid, name, price, size) values('74', 'диск сцепления', '7586','20');
INSERT INTO detail(detailid, name, price, size) values('75', 'спойлер', '13923','20');
INSERT INTO detail(detailid, name, price, size) values('76', 'подвеска', '12910','50');
INSERT INTO detail(detailid, name, price, size) values('77', 'стептроник', '17809','50');
INSERT INTO detail(detailid, name, price, size) values('78', 'сигнализация', '17599','20');
INSERT INTO detail(detailid, name, price, size) values('79', 'автомагнитола', '14735','10');
INSERT INTO detail(detailid, name, price, size) values('80', 'подушка безопасности', '6485','50');
INSERT INTO detail(detailid, name, price, size) values('81', 'аэродинамический обвес', '16888','10');
INSERT INTO detail(detailid, name, price, size) values('82', 'рычаг стабилизатора поперечной устойчивости', '10401','30');
INSERT INTO detail(detailid, name, price, size) values('83', 'картер', '15815','50');
INSERT INTO detail(detailid, name, price, size) values('84', 'дифференцм=иал', '8666','30');
INSERT INTO detail(detailid, name, price, size) values('85', 'редуктор', '17824','40');
INSERT INTO detail(detailid, name, price, size) values('86', 'карбюратор', '1630','30');
INSERT INTO detail(detailid, name, price, size) values('87', 'инжектор', '12299','10');
INSERT INTO detail(detailid, name, price, size) values('88', 'стартер', '12409','30');
INSERT INTO detail(detailid, name, price, size) values('89', 'кардан', '15873','30');
INSERT INTO detail(detailid, name, price, size) values('90', 'впускной коллектор', '14545','20');
INSERT INTO detail(detailid, name, price, size) values('91', 'выпускной коллектор', '2703','40');
INSERT INTO detail(detailid, name, price, size) values('92', 'сальники', '231','50');
INSERT INTO detail(detailid, name, price, size) values('93', 'маслосъёмные кольца', '1749','20');
INSERT INTO detail(detailid, name, price, size) values('94', 'реле', '9167','40');
INSERT INTO detail(detailid, name, price, size) values('95', 'тахометр', '4726','40');
INSERT INTO detail(detailid, name, price, size) values('96', 'релинг', '3534','30');
INSERT INTO detail(detailid, name, price, size) values('97', 'преднатяжители ремней', '2396','50');
INSERT INTO detail(detailid, name, price, size) values('98', 'климат контроль', '20','30');
INSERT INTO detail(detailid, name, price, size) values('99', 'воздушный фильтр', '11490','50');
INSERT INTO detail(detailid, name, price, size) values('100', 'масляный фильтр', '9184','40');